Repository EasyRPG/liblcf, pull requests merged in 2018-11, with the labels that each got.

#266 Increment save counts when writing LDB, LMU, and LSD
  src/ldb_reader.cpp
  src/ldb_reader.h
  src/lmu_reader.cpp
  src/lmu_reader.h
  src/lsd_reader.cpp
  src/lsd_reader.h
Labels: Savegames

#276 Fix compiler warnings on EnumTags
  src/enum_tags.h
Labels: Building

#268 Bitperfect copying of LSD
  CMakeLists.txt
  Makefile.am
  builds/vs2015/liblcf.vcxproj
  generator/csv/fields.csv
  generator/csv/setup.csv
  generator/csv/structs.csv
  generator/generate.py
  generator/templates/rpg_header.tmpl
  src/generated/ldb_animationtiming.cpp
  src/generated/ldb_music.cpp
  src/generated/ldb_skill.cpp
  src/generated/ldb_system.cpp
  src/generated/ldb_terrain.cpp
  src/generated/lmt_mapinfo.cpp
  src/generated/lmu_eventpagecondition.cpp
  src/generated/lmu_map.cpp
  src/generated/lsd_chunks.h
  src/generated/lsd_saveactor.cpp
  src/generated/lsd_savemapevent.cpp
  src/generated/lsd_savepartylocation.cpp
  src/generated/lsd_savesystem.cpp
  src/generated/lsd_savevehiclelocation.cpp
  src/generated/rpg_eventpagecondition.h
  src/generated/rpg_mapinfo.cpp
  src/generated/rpg_mapinfo.h
  src/generated/rpg_music.h
  src/generated/rpg_savepicture.h
  src/generated/rpg_sound.h
  src/generated/rpg_terrain.h
  src/generated/rpg_trooppagecondition.h
  src/reader_struct.h
  src/rpg_setup.cpp
Labels: Savegames

#275 Add cmake config to autotools-based installs
  Makefile.am
  builds/liblcf-config.cmake.in
Labels: Building

#283 Fix SaveActor::row
  generator/csv/enums.csv
  generator/csv/fields.csv
  src/generated/lsd_chunks.h
  src/generated/rpg_enums.cpp
  src/generated/rpg_saveactor.h
  src/rpg_setup.cpp
Labels: Chunks, Savegames

#282 Implement structs inheritance with SaveMapEventBase
  CMakeLists.txt
  Makefile.am
  builds/vs2015/liblcf.vcxproj
  generator/csv/fields.csv
  generator/csv/setup.csv
  generator/csv/structs.csv
  generator/generate.py
  generator/templates/chunks.tmpl
  generator/templates/reader.tmpl
  generator/templates/rpg_header.tmpl
  src/generated/lsd_chunks.h
  src/generated/lsd_savemapevent.cpp
  src/generated/lsd_savemapeventbase.cpp
  src/generated/lsd_savepartylocation.cpp
  src/generated/lsd_savevehiclelocation.cpp
  src/generated/rpg_savemapevent.h
  src/generated/rpg_savemapeventbase.h
  src/generated/rpg_savepartylocation.h
  src/generated/rpg_savevehiclelocation.h
  src/rpg_fixup.cpp
  src/rpg_setup.cpp
Labels: Refactor, Savegames
