Repository EasyRPG/liblcf, pull requests merged in 2018-12, with the labels that each got.

#273 Optimize String Parsing routines
  CMakeLists.txt
  Makefile.am
  builds/vs2015/liblcf.vcxproj
  src/encoder.cpp
  src/encoder.h
  src/reader_lcf.cpp
  src/reader_lcf.h
  src/reader_util.cpp
  src/scope_guard.h
  src/writer_lcf.cpp
  src/writer_lcf.h
Labels: Performance, Refactor

#294 Remove MSVC project
  .gitignore
  CMakeLists.txt
  Makefile.am
  README.md
  builds/cmake/Modules/ConfigureWindows.cmake
  builds/vs2015/PropertySheet.props
  builds/vs2015/liblcf.vcxproj
  builds/vs2015/liblcf.vcxproj.filters
  src/encoder.cpp
  src/reader_util.cpp
Labels: Building

#292 Composite Characters Fix
  src/reader_util.cpp
  src/reader_util.h
Labels: Encoding

#298 Small Maintenance
  .gitattributes
  CMakeLists.txt
  Makefile.am
  README.md
  builds/sources2buildsystem.pl
  tests/doctest.h
Labels: Building
