Repository EasyRPG/liblcf, pull requests merged in 2019-02, with the labels that each got.

#307 Create icu::UnicodeString with UTF-8 codepage, fixes normalize on Windows
  src/reader_util.cpp
Labels: Encoding

#308 Add FlagSet<E.N> for wrapping a bitset of enum values
  CMakeLists.txt
  Makefile.am
  src/flag_set.h
  tests/flag_set.cpp
Labels: Enhancement

#309 Fix compilation error when LCF_SUPPORT_ICU is not defined in reader_util.cpp
  src/reader_util.cpp
Labels: Building

#310 Fix MapEvent waiting and trigger chunks
  generator/csv/fields.csv
  src/generated/lsd_chunks.h
  src/generated/lsd_savemapevent.cpp
  src/generated/rpg_savemapevent.h
Labels: Chunks
