Repository EasyRPG/liblcf, pull requests merged in 2020-09, with the labels that each got.

#391 Rename message_active -> event_message_active
  generator/csv/fields.csv
  src/generated/lcf/lsd/chunks.h
  src/generated/lcf/rpg/savesystem.h
  src/generated/lsd_saveactor.cpp
  src/generated/lsd_savesystem.cpp
  src/generated/rpg_savesystem.cpp
  src/rpg_setup.cpp
Labels: Chunks

#390 Optimize memory with DBBitArray
  CMakeLists.txt
  Makefile.am
  generator/csv/fields.csv
  generator/generate.py
  src/generated/lcf/rpg/item.h
  src/generated/lcf/rpg/skill.h
  src/generated/lcf/rpg/troop.h
  src/generated/ldb_item.cpp
  src/generated/ldb_skill.cpp
  src/generated/ldb_troop.cpp
  src/lcf/dbbitarray.h
  src/lcf/reader_lcf.h
  src/lcf/writer_lcf.h
  src/reader_lcf.cpp
  src/reader_struct.h
  src/reader_xml.cpp
  src/writer_lcf.cpp
  src/writer_xml.cpp
  tests/dbbitarray.cpp
Labels: Performance

#393 Compiler Warning fixes
  src/lcf/dbarray.h
  src/lcf/dbarrayalloc.h
  src/lcf/dbbitarray.h
  src/lcf/dbstring.h
  src/reader_struct.h
Labels: Building

#400 Force nonstd string_view and span to fix C++17/20 interop
  src/dbarray.cpp
  src/lcf/dbarrayalloc.h
  src/lcf/span.h
  src/lcf/string_view.h
Labels: Building

#401 make _empty_buf const instead of constexpr
  src/dbarray.cpp
  src/lcf/dbarrayalloc.h
Labels: Building

#399 Remove SaveActor Fixup And Setup
  generator/csv/constants.csv
  generator/csv/fields.csv
  generator/csv/functions.csv
  generator/generate.py
  src/generated/lcf/rpg/saveactor.h
  src/generated/lcf/rpg/saveinventory.h
  src/generated/lcf/rpg/savemapevent.h
  src/generated/lsd_saveactor.cpp
  src/generated/rpg_saveactor.cpp
  src/lsd_reader.cpp
  src/rpg_fixup.cpp
  src/rpg_setup.cpp
Labels: Chunks
