Repository EasyRPG/liblcf, pull requests merged in 2024-03, with the labels that each got.

#474 Update workflow and cmakery
  .github/workflows/stable-compilation.yml
  CMakeLists.txt
  builds/cmake/Modules/MiscUtils.cmake
Labels: Building

#473 Maniacs Feature: Add separate Width/Height parameters for scaling pictures
  generator/csv/fields_easyrpg.csv
  src/generated/lcf/lsd/chunks.h
  src/generated/lcf/rpg/savepicture.h
  src/generated/lsd_savepicture.cpp
  src/generated/rpg_savepicture.cpp
Labels: Chunks

#416 Allow redirection of lcf console messages
  CMakeLists.txt
  Makefile.am
  src/dbstring_struct.cpp
  src/encoder.cpp
  src/lcf/log_handler.h
  src/lcf/reader_xml.h
  src/ldb_equipment.cpp
  src/ldb_eventcommand.cpp
  src/ldb_parameters.cpp
  src/ldb_reader.cpp
  src/lmt_reader.cpp
  src/lmt_rect.cpp
  src/lmt_treemap.cpp
  src/lmu_movecommand.cpp
  src/lmu_reader.cpp
  src/log.h
  src/log_handler.cpp
  src/lsd_reader.cpp
  src/reader_flags.cpp
  src/reader_lcf.cpp
  src/reader_struct.h
  src/reader_struct_impl.h
  src/reader_util.cpp
  src/reader_xml.cpp
Labels: RFC, Enhancement

#477 Fix building for Android
  src/reader_lcf.cpp
  src/reader_struct.h
  src/writer_lcf.cpp
Labels: Building
